export default [
  {
    houseName: '機房1',
    url: 'glTF/plane.glb',
    cabinets: [
      {
        cabinetName: 'cabinet1',
        x: 3,
        z: 3,
        url: 'glTF/cabinets.glb',
        servers: [
          { name: 'sony', y: 0.5 },
          { name: 'sony', y: 0.76 },
          { name: 'sony', y: 0 },
          { name: 'sony', y: 0 },
          { name: 'sony', y: 4 },
          { name: 'sony', y: 5 },
        ],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 6,
        z: 3,
        servers: [
          { name: 'sony', y: 0 },
          { name: 'sony', y: 1 },
          { name: 'sony', y: 2 },
          { name: 'sony', y: 3 },
          { name: 'sony', y: 4 },
          { name: 'sony', y: 5 },
        ],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 9,
        z: 3,
        servers: [
          { name: 'sony', y: 0 },
          { name: 'sony', y: 1 },
          { name: 'sony', y: 2 },
          { name: 'sony', y: 3 },
          { name: 'sony', y: 4 },
          { name: 'sony', y: 5 },
        ],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 12,
        z: 3,
        servers: [
          { name: 'sony', y: 0 },
          { name: 'sony', y: 1 },
          { name: 'sony', y: 2 },
          { name: 'sony', y: 3 },
          { name: 'sony', y: 4 },
          { name: 'sony', y: 5 },
        ],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 15,
        z: 3,
        servers: [
          { name: 'sony', y: 0 },
          { name: 'sony', y: 1 },
          { name: 'sony', y: 2 },
          { name: 'sony', y: 3 },
          { name: 'sony', y: 4 },
          { name: 'sony', y: 5 },
        ],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 18,
        z: 3,
        servers: [
          { name: 'sony', y: 0 },
          { name: 'sony', y: 1 },
          { name: 'sony', y: 2 },
          { name: 'sony', y: 3 },
          { name: 'sony', y: 4 },
          { name: 'sony', y: 5 },
        ],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 21,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 24,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 27,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 30,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 33,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 36,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 39,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 42,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 45,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 48,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 51,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 54,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 57,
        z: 3,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 3,
        z: 10,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 6,
        z: 10,
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        x: 9,
        z: 10,
        servers: [{ name: 'sony', y: 0 }],
      },
    ],
  },
  {
    houseName: '機房2',
    url: 'glTF/plane2.glb',
    cabinets: [
      {
        cabinetName: 'cabinet1',
        // x: 10,
        // z: 10,
        url: 'glTF/cabinets.glb',
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        // x: 0,
        // z: 10,
        url: 'glTF/cabinets.glb',
        servers: [{ name: 'sony', y: 0 }],
      },
    ],
  },
  {
    houseName: '機房3',
    url: 'glTF/plane.glb',
    cabinets: [
      {
        cabinetName: 'cabinet1',
        url: 'glTF/cabinets.glb',
        servers: [{ name: 'sony', y: 0 }],
      },
      {
        cabinetName: 'cabinet2',
        url: 'glTF/cabinets.glb',
        servers: [{ name: 'sony', y: 0 }],
      },
    ],
  },
]
